apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: backend
type: Opaque
data:
  DB_USER: cmVhY3R0ZXN0MTIz ##Base64 encoded username: reactuser
  DB_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjM= ##Base64 encoded password: StrongPassword123
